config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'review/show'
  end
  namespace :admin do
    get 'items/index'
    get 'items/show'
    get 'items/new'
  end
  namespace :public do
    get 'items/index'
    get 'items/show'
  end
  namespace :public do
    get 'reviews/new'
    get 'reviews/index'
    get 'reviews/show'
    get 'reviews/edit'
  end


  # 顧客用
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }



  # 顧客用リソース
  root to: "public/homes#top"
    get "about", to: "public/homes#about", as: "homes_about"
  scope module: :public do

    get 'mypage', to: 'users#mypage', as: 'mypage'

    resources :items, only: [:new, :create, :index, :show] do
      resources :reviews, only: [:new, :create, :show, :edit, :update, :destroy] do
        resources :comments, only: [:create, :destroy]
      end
    end
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get :followings
        get :followers
      end
      resource :relationship, only: [:create, :destroy]
    end
  end

  # 管理者用リソース
  namespace :admin do
    root to: "homes#top"
    resources :items do
      resources :reviews, only: [:show, :destroy]
    end
    resources :users, only: [:index, :show, :destroy]
  end

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_one_attached :item_image

  validates :title,presence:true

  def get_item_image
    if item_image.attached?
      item_image
    else
      'no_image.jpg'
    end
  end

  # 平均評価を計算して小数点第1位まで返すメソッド
  def avg_score
    unless self.reviews.empty?
      # 平均を計算し、round(1)で四捨五入して小数点第1位まで表示
      reviews.average(:star).round(1).to_f
    else
      0.0
    end
  end

  # Ransackの設定：ItemからReview、そしてReviewからTagへの検索を許可
  def self.ransackable_associations(auth_object = nil)
    ["reviews"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["body", "created_at", "id", "title", "updated_at"]
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.all
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "商品情報を更新しました。"
      redirect_to admin_items_path
    else
      flash[:alert] = "商品情報の更新に失敗しました。"
      render "edit"
    end
  end


  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to admin_items_path, notice: 'アイテムを削除しました。'
  end

  private

  def item_params
    params.require(:item).permit(:title, :body, :item_image)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class='container py-5'>
  <div class='row justify-content-center'>
    <div class='col-md-10 col-lg-6'>
      <div class="comment-form px-3">
          <h4>商品内容を変更する</h4>
            <%= form_with model: [:admin, @item], local: true do |f| %>
              <div class="form-group">
                <%= f.label :商品名 %>
                <%= f.text_field :title, class: 'form-control item_title' %>
              </div>
              <div class="form-group">
                <%= f.label :内容（任意） %>
                <%= f.text_area :body, class: 'form-control item_body' %>
              </div>
              <div class="form-group">
                <%= f.label :item_image, "商品画像（任意）" %>
                <%= f.file_field :item_image, class: "form-control-file" %>
              </div>
              <div class="form-group">
                <%= f.submit '送信', class: "btn btn-primary px-4" %>
              </div>
            <% end %>
            <div class="pt-1">
              <%= link_to "削除する", admin_item_path, method: :delete, class: "btn btn-danger", data: {confirm:"アイテムを削除してもいいですか？"} %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class='container py-5'>
  <div class='row'>
    <div class='col-9 mx-auto'>
      <div class="row mb-3 align-items-center">
        <div class="col-md-4">
          <h4>アイテム</h4>
        </div>
        <div class="col-md-8 text-right">
          <%= link_to "新規登録", new_item_path, class: 'btn btn-primary'%>
        </div>
      </div>

      <table class="table table-hover">
        <thead> <tr>
            <th style="width: 10%;">アイテムID</th>
            <th style="width: 20%;">アイテム画像</th>
            <th style="width: 20%;">名称</th>
            <th style="width: 20%;">レビュー数</th>
            <th style="width: 20%;"></th>
            <th style="width: 10%;"></th>
          </tr>
        </thead>

        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td><%= item.id %></td>
              <td><%= image_tag item.get_item_image, size:'100x65' %></td>
              <td><%= item.title %></td>
              <td><%= item.reviews.count %></td>
              <td><%= link_to "詳細", item_path(item.id), class: "btn btn-primary" %></td>
              <td><%= link_to "編集", edit_admin_item_path(item.id), class: "btn btn-success" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>