config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'review/show'
  end
  namespace :admin do
    get 'items/index'
    get 'items/show'
    get 'items/new'
  end
  namespace :public do
    get 'items/index'
    get 'items/show'
  end
  namespace :public do
    get 'reviews/new'
    get 'reviews/index'
    get 'reviews/show'
    get 'reviews/edit'
  end


  # 顧客用
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }



  # 顧客用リソース
  root to: "public/homes#top"
    get "about", to: "public/homes#about", as: "homes_about"
  scope module: :public do

    get 'mypage', to: 'users#mypage', as: 'mypage'

    resources :items, only: [:new, :create, :index, :show] do
      resources :reviews, only: [:new, :create, :show, :edit, :update, :destroy] do
        resources :comments, only: [:create, :destroy]
      end
    end
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get :followings
        get :followers
      end
      resource :relationship, only: [:create, :destroy]
    end
  end

  # 管理者用リソース
  namespace :admin do
    root to: "homes#top"
    resources :items do
      resources :reviews, only: [:show, :destroy]
    end
    resources :users, only: [:index, :show, :destroy]
  end

end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_item
  before_action :set_review_and_item, only: [:show, :destroy]
  def show
  end

  def destroy
    if @review.destroy
      redirect_to admin_root_path, notice: 'レビューを削除しました。'
    else
      redirect_to admin_root_path, alert: '削除に失敗しました。'
    end
  end

end

private

  def review_params
    params.require(:review).permit(:title, :body, :star)
  end

  # :item_id から @item を見つける
  def set_item
    @item = Item.find(params[:item_id])
  end
  
  # :id から @review を見つけ、@review から @item を見つける
  def set_review_and_item
    @review = Review.find(params[:id])
    @item = @review.item
  end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/views/admin/reviews/show.html.erb
<div class='container py-5'>
  <div class='row'>
    <div class='col-md-12'>
      <div class='row'>
        <div class="description-scroll col-6 px-3">  
          <h3><strong><%= @review.title %></strong></h3>
          <%= render "public/shared/star", review: @review %>
          <p class="description-scroll p-3">
            商品名：<%= link_to @item.title, item_path(@item) %><br>
            投稿者：<%= link_to @review.user.name, admin_user_path(@review) %><br>
            投稿日時：<%= @review.created_at %><br>
            最終更新日時：<%= @review.updated_at %>
          </p>
          <p class="description-scroll px-3">
            <%= @review.body %>
          </p>
        </div>
      </div>
      <div class="p-3">
        <%= link_to "削除する", admin_item_review_path(@item, @review), method: :delete, class: "btn btn-danger", data: {confirm:"Are you sure?"} %>
      </div>
      <div class="p-3">
        <h4></h4>
      </div>
    </div>
  </div>
</div>