config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'review/show'
  end
  namespace :admin do
    get 'items/index'
    get 'items/show'
    get 'items/new'
  end
  namespace :public do
    get 'items/index'
    get 'items/show'
  end
  namespace :public do
    get 'reviews/new'
    get 'reviews/index'
    get 'reviews/show'
    get 'reviews/edit'
  end


  # 顧客用
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }



  # 顧客用リソース
  root to: "public/homes#top"
    get "about", to: "public/homes#about", as: "homes_about"
  scope module: :public do

    get 'mypage', to: 'users#mypage', as: 'mypage'

    resources :items, only: [:new, :create, :index, :show] do
      resources :reviews, only: [:new, :create, :show, :edit, :update, :destroy] do
        resources :comments, only: [:create, :destroy]
      end
    end
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get :followings
        get :followers
      end
      resource :relationship, only: [:create, :destroy]
    end
  end

  # 管理者用リソース
  namespace :admin do
    root to: "homes#top"
    resources :items do
      resources :reviews, only: [:show, :destroy]
    end
    resources :users, only: [:index, :show, :destroy]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy

  # フォローしている側の関係
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed

  # フォローされている側の関係
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  
  validates :name, length: { maximum: 20 }, presence:true
  validates :email,presence:true

  GUEST_USER_EMAIL = "guest@example.com"

  has_one_attached :user_image

  # Ransackの設定：検索可能な属性を定義
  def self.ransackable_attributes(auth_object = nil)
    ["name", "created_at"] 
  end

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
    end
  end
  def get_user_image
    if user_image.attached?
      user_image
    else
      'no_image.jpg'
    end
  end

  def following?(user)
    followings.exists?(id: user.id)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
  end
  def destroy
      @user = User.find(params[:id])
      @user.destroy
      redirect_to admin_users_path, notice: 'ユーザーを削除しました。'
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.erb
<div class='container py-5'>
  <div class='row'>
    <div class='col-9 mx-auto'>
      <div class="row mb-3 align-items-center">
        <div class="col-md-4">
          <h4>ユーザー</h4>
        </div>
      </div>

      <table class="table table-hover">
        <thead> <tr>
            <th style="width: 10%;">ユーザーID</th>
            <th style="width: 30%;">プロフィール画像</th>
            <th style="width: 30%;">アカウント名</th>
            <th style="width: 20%;">emailアドレス</th>
            <th style="width: 10%;">レビュー数</th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td><%= image_tag user.get_user_image, size:'100x100' %></td>
              <td><%= link_to user.name, admin_user_path(user.id) %></td>
              <td><%= user.email %></td>
              <td><%= user.reviews.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class='container py-5'>
  <div class='row'>
    <div class='col-md-12'>
      <div class='row'>
        <div class="description-scroll col-3 px-3">  
          <%= image_tag @user.get_user_image, size:'200x200' %>
        </div>
        <div class="description-scroll col-6 px-3">  
          <h2><%= @user.name %></h2>
          
          <h5 class="p-3"><%= link_to @user.followings.count, followings_user_path(@user) %> フォロー</h5>
          <h5 class="px-3"><%= link_to @user.followers.count, followers_user_path(@user) %> フォロワー</h5>
            <div class="p-3">
          <%= link_to "削除する", admin_user_path, method: :delete, class: "btn btn-danger", data: {confirm:"ユーザーを削除してもいいですか？"} %>
          </div>
        </div>
      </div>
      <div class="d-flex justify-content-between align-items-center my-4 border-bottom pb-2">
        <h4 class="mb-0">
          <i class="fas fa-list-ul"></i> 投稿したレビュー
        </h4>
      </div>
      <div class="card mb-3 shadow-sm hover-card">
        <div class="card-body">
          <% @user.reviews.each do |review| %>
            <div class="px-3 py-2">
              <div class="d-flex justify-content-between">
                <h5>
                  <%= link_to review.title, item_review_path(@user, review) %><br>
                  <%= render "public/shared/star", review: review %>
                </h5>
                <small class="text-muted"><%= review.created_at.strftime('%Y/%m/%d') %></small>
              </div>
              <strong><i class="fa-box-open text-primary"></i><%= review.item.title %></strong><br>
              <div class="mb-2">
                <i class="fas fa-tags text-primary"></i>
                <% review.tag_list.each do |tag| %>
                  <span class="badge badge-info"><%= tag %></span>
                <% end %>
              </div>
              <p class="card-text text-secondary mb-0">
                <%= truncate(review.body, length: 100) %>
              </p>
              <% if review.body.length > 100 %>
                <div class="text-right mt-1">
                  <%= link_to "詳細を見る", item_review_path(@item, review), class: "small" %>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>