config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'review/show'
  end
  namespace :admin do
    get 'items/index'
    get 'items/show'
    get 'items/new'
  end
  namespace :public do
    get 'items/index'
    get 'items/show'
  end
  namespace :public do
    get 'reviews/new'
    get 'reviews/index'
    get 'reviews/show'
    get 'reviews/edit'
  end


  # 顧客用
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }



  # 顧客用リソース
  root to: "public/homes#top"
    get "about", to: "public/homes#about", as: "homes_about"
  scope module: :public do

    get 'mypage', to: 'users#mypage', as: 'mypage'

    resources :items, only: [:new, :create, :index, :show] do
      resources :reviews, only: [:new, :create, :show, :edit, :update, :destroy] do
        resources :comments, only: [:create, :destroy]
      end
    end
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      member do
        get :followings
        get :followers
      end
      resource :relationship, only: [:create, :destroy]
    end
  end

  # 管理者用リソース
  namespace :admin do
    root to: "homes#top"
    resources :items do
      resources :reviews, only: [:show, :destroy]
    end
    resources :users, only: [:index, :show, :destroy]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review
  belongs_to :user
  validates :body,presence:true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_one_attached :item_image

  validates :title,presence:true

  def get_item_image
    if item_image.attached?
      item_image
    else
      'no_image.jpg'
    end
  end

  # 平均評価を計算して小数点第1位まで返すメソッド
  def avg_score
    unless self.reviews.empty?
      # 平均を計算し、round(1)で四捨五入して小数点第1位まで表示
      reviews.average(:star).round(1).to_f
    else
      0.0
    end
  end

  # Ransackの設定：ItemからReview、そしてReviewからTagへの検索を許可
  def self.ransackable_associations(auth_object = nil)
    ["reviews"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["body", "created_at", "id", "title", "updated_at"]
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, uniqueness: {scope: :followed_id}

end

app/models/review.rb
class Review < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
  belongs_to :item
  validates :title, length: { maximum: 20 },presence:true
  validates :body, length: { maximum: 99 },presence:true
  validates :star,presence:true

  # タグ機能の有効化
  acts_as_taggable

  # Ransackの設定：検索可能な属性
  def self.ransackable_attributes(auth_object = nil)
    ["title", "created_at"] 
  end

  # Ransackの設定：検索可能な関連（タグへのアクセスを許可）
  def self.ransackable_associations(auth_object = nil)
    ["tags"]
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy

  # フォローしている側の関係
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed

  # フォローされている側の関係
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  
  validates :name, length: { maximum: 20 }, presence:true
  validates :email,presence:true

  GUEST_USER_EMAIL = "guest@example.com"

  has_one_attached :user_image

  # Ransackの設定：検索可能な属性を定義
  def self.ransackable_attributes(auth_object = nil)
    ["name", "created_at"] 
  end

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
    end
  end
  def get_user_image
    if user_image.attached?
      user_image
    else
      'no_image.jpg'
    end
  end

  def following?(user)
    followings.exists?(id: user.id)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @reviews = Review.all.order(created_at: :desc).includes(:item)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.all
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "商品情報を更新しました。"
      redirect_to admin_items_path
    else
      flash[:alert] = "商品情報の更新に失敗しました。"
      render "edit"
    end
  end


  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to admin_items_path, notice: 'アイテムを削除しました。'
  end

  private

  def item_params
    params.require(:item).permit(:title, :body, :item_image)
  end

end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_item
  before_action :set_review_and_item, only: [:show, :destroy]
  def show
  end

  def destroy
    if @review.destroy
      redirect_to admin_root_path, notice: 'レビューを削除しました。'
    else
      redirect_to admin_root_path, alert: '削除に失敗しました。'
    end
  end

end

private

  def review_params
    params.require(:review).permit(:title, :body, :star)
  end

  # :item_id から @item を見つける
  def set_item
    @item = Item.find(params[:item_id])
  end
  
  # :id から @review を見つけ、@review から @item を見つける
  def set_review_and_item
    @review = Review.find(params[:id])
    @item = @review.item
  end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
  end
  def destroy
      @user = User.find(params[:id])
      @user.destroy
      redirect_to admin_users_path, notice: 'ユーザーを削除しました。'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_q


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:name])
  end

  private

  def set_q
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
    @result = params[:q]&.values&.reject(&:blank?)
  end

end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_flash_message.html.erb
<% if flash[:notice] %>
  <p class="alert alert-success"><%= notice %></p>
<% elsif flash[:alert] %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
      <a class="navbar-brand" href="/"><span>ReviewMate</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
          <li>
            <%= link_to admin_root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> トップ
            <% end %>
          </li>
          <li>
            <%= link_to admin_users_path,class: 'nav-link text-light' do %>
              <i class="fa-solid fa-user"></i> ユーザ一覧
            <% end %>
          </li>
          <li>
            <%= link_to admin_items_path,class: 'nav-link text-light' do %>
              <i class="fas fa-box-open"></i> 商品一覧
            <% end %>
          </li>
          <li>
            <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
            <% end %>
          </li>
        <% elsif user_signed_in? %>
          <li>
            <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%= link_to homes_about_path,class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i> About
            <% end %>
          </li>
          <li>
            <%= link_to items_path,class: 'nav-link text-light' do %>
              <i class="fas fa-box-open"></i> 商品
            <% end %>
          </li>
          <li>
            <%= link_to new_item_path,class: 'nav-link text-light' do %>
              <i class="fa-solid fa-plus"></i> 商品登録
            <% end %>
          </li>
          <li>
            <%= link_to mypage_path,class: 'nav-link text-light' do %>
              <i class="fa-solid fa-user"></i> マイページ
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%= link_to homes_about_path,class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i> About
            <% end %>
          </li>
          <li>
            <%= link_to items_path,class: 'nav-link text-light' do %>
              <i class="fas fa-box-open"></i> 商品
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> 新規登録
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> ログイン
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReviewMate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/015e7b3d71.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <main>
        <%= render 'layouts/flash_message' %>
        <%= yield %>
      </main>
  </body>
</html>